openapi: 3.0.2
info:
  title: Cruddur Backend API
  version: '1.0'
servers:
  - url: 'https://api.server.test/v1'
paths:
  /api/activities/notifications:
    $ref: paths/api@activities@notifications.yaml
  /api/activities/home:
    $ref: paths/api@activities@home.yaml
  /api/activities/search:
    $ref: paths/api@activities@search.yaml
  /api/activities:
    $ref: paths/api@activities.yaml
  '/api/activities/@{handle}':
    $ref: 'paths/api@activities@@{handle}.yaml'
  /api/message_groups:
    $ref: paths/api@message_groups.yaml
  '/api/messages/@{handle}':
    $ref: 'paths/api@messages@@{handle}.yaml'
  /api/messages:
    $ref: paths/api@messages.yaml
