
# Base Image ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#FROM redocly/cli:latest as build
FROM node:16.18 as build

COPY . /backend-flask-api-docs
WORKDIR /backend-flask-api-docs
RUN ls
RUN npx @redocly/cli build-docs openapi.yml

# New Base Image ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FROM nginx:1.23.3-alpine

# --from build is coming from the Base Image
COPY --from=build /backend-flask-api-docs/redoc-static.html /usr/share/nginx/html/
COPY --from=build /backend-flask-api-docs/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3001